Add Guild JSdocs
NatsukiBot/db pull request #22
Opened 2018-07-21 19:27 UTC by jasonhaxstuff

I said I wasn't done, I thought you would leave it open and wait for the rest. I still have Referrals and Users to go.

2018-07-21 19:49 UTC, tannerz28 commented
Oh, woops.

2018-07-22 05:12 UTC, jasonhaxstuff commented
I'll add the User docs in a whole other thing, because those are going to be something to tackle through. They'll be bunched together with another PR down the road.

2018-07-22 05:42 UTC, tgoins requested changes

2018-07-22 05:42 UTC, tannerz28 commented on src/entity/Guild/GuildSuggestion.ts
> +   * The amount of likes/thumbs up the suggestion has gotten.
Changed `gotten` to `received`

2018-07-22 05:42 UTC, tannerz28 commented on src/entity/Guild/GuildSuggestion.ts
> +   * The amount of dislikes/thumbs down the suggestion has gotten.
Changed `gotten` to `received`

2018-07-22 05:45 UTC, tgoins approved these changes

2018-07-22 05:45 UTC, merged